services:
  ffc-techspike-customer-registry:
    build:
      context: .
      target: production
    image: ffc-techspike-customer-registry
    container_name: ffc-techspike-customer-registry
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-techspike-customer-registry-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      COSMOS_ENDPOINT: ${COSMOS_ENDPOINT}
      COSMOS_KEY: ${COSMOS_KEY}
      COSMOS_DATABASE: ${COSMOS_DATABASE}
      COSMOS_CONTAINER: ${COSMOS_CONTAINER}
