services:
  ffc-techspike-customer-registry:
    build:
      context: .
      target: production
    image: ffc-techspike-customer-registry
    container_name: ffc-techspike-customer-registry
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-techspike-customer-registry-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
      AZURE_STORAGE_CONNECTION_STRING: ${AZURE_STORAGE_CONNECTION_STRING:-AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;DefaultEndpointsProtocol=http;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;QueueEndpoint=http://127.0.0.1:10001/devstoreaccount1;TableEndpoint=http://127.0.0.1:10002/devstoreaccount1;}
      AZURE_STORAGE_USE_CONNECTION_STRING: "true"
      COSMOS_ENDPOINT: ${COSMOS_ENDPOINT}
      COSMOS_KEY: ${COSMOS_KEY}
      COSMOS_DATABASE: ${COSMOS_DATABASE}
      COSMOS_CONTAINER: ${COSMOS_CONTAINER}
      LAND_ENDPOINT: ${LAND_ENDPOINT:- https://environment.data.gov.uk/arcgis/rest/services/RPA/}
      AHWR_ENDPOINT: ${AHWR_ENDPOINT:- http://host.docker.internal:3001/api/}
      AHWR_PAYMENT_ENDPOINT: ${AHWR_PAYMENT_ENDPOINT:- http://host.docker.internal:3005/api/}
      SEARCH_ENDPOINT: ${SEARCH_ENDPOINT}
      SEARCH_KEY: ${SEARCH_KEY}
      SEARCH_INDEX: ${SEARCH_INDEX}
