environment: development
name: ffc-techspike-customer-registry
namespace: ffc-techspike
workstream: ffc-techspike
image: ffc-techspike-customer-registry

labels: {}

appInsights:
  key:

containerConfigMap:
  name: ffc-techspike-customer-registry-config-map

containerSecret:
  name: ffc-techspike-customer-registry-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  cosmosEndpoint:
  cosmoskey:
  cosmosDatabase:
  cosmosContainer:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 40Mi
  limitCpu: 40m
  port: 3000

livenessProbe:
  path: /healthz
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  path: /healthy
  port: 3000
  initialDelaySeconds: 10
  periodSeconds: 10
  failureThreshold: 3
