{{- include "ffc-helm-library.container-config-map" (list . "ffc-techspike-customer-registry.config-map") -}}
{{- define "ffc-techspike-customer-registry.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  COSMOS_ENDPOINT: {{ quote .Values.container.cosmosEndpoint }}
  COSMOS_DATABASE: {{ quote .Values.container.cosmosDatabase }}
  COSMOS_CONTAINER: {{ quote .Values.container.cosmosContainer }}
{{- end -}}
