{{- include "ffc-helm-library.container-secret" (list . "ffc-techspike-customer-registry.container-secret") -}}
{{- define "ffc-techspike-customer-registry.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
  COSMOS_KEY: {{ quote .Values.container.cosmoskey }}
{{- end -}}
